AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Timestream Writer Lambda

Globals:
  Function:
    Timeout: 30

Parameters:
  DatabaseName:
    Type: String
    Description: Name of the Timestream database
  TableName:
    Type: String
    Description: Name of the Timestream table
  WriteInterval:
    Type: Number
    Description: Interval in minutes for writing data

Resources:
  TimestreamWriterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./fake-factory
      Handler: app.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          # !Ref is used to reference JUST the parameter value
          DATABASE_NAME: !Ref DatabaseName
          TABLE_NAME: !Ref TableName
          WRITE_INTERVAL: !Ref WriteInterval
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            # !Sub is used to reference the variable within a longer string 
            Schedule: !Sub rate(${WriteInterval} minute)
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - timestream:WriteRecords
              Resource: !Sub arn:aws:timestream:${AWS::Region}:${AWS::AccountId}:database/${DatabaseName}/table/${TableName}
            - Effect: Allow
              Action:
                - timestream:DescribeEndpoints
              Resource: "*"

Outputs:
  TimestreamWriterFunction:
    Description: "Timestream Writer Lambda Function ARN"
    Value: !GetAtt TimestreamWriterFunction.Arn
  TimestreamWriterFunctionIamRole:
    Description: "Implicit IAM Role created for Timestream Writer function"
    Value: !GetAtt TimestreamWriterFunctionRole.Arn